Repository team-p4-5/ICT2101-p4-5, pull requests merged in 2021-11, with the labels that each got.

#70 [MODIFIED] Project's README.md has been updated with team workflow
  README.md
Labels: management

#71 [MODIFIED] Project's README.md has been updated with PR approval SOP
  README.md
Labels: management

#75 Merge to add team's project .gitignore
  .gitattributes
  .gitignore
  .idea/.gitignore
  .idea/ICT2101_P4_5.iml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
Labels: management

#92 Corrected branch naming convention from documentation/... -> management/...
  README.md
Labels: management

#93 Merge Completed Tooltip (ui/tooltip branch) to dev
  app/static/css/tooltip.css
  app/static/js/tour.js
  app/templates/control2.html
Labels: ui

#97 Merging completed "db_management" feature into dev
  .gitignore
  app/__init__.py
  app/libraries/DatabaseManagement.py
  app/libraries/utils.py
Labels: backend

#100 Merging completed backend data structure (Class) definitions into dev
  app/__init__.py
  app/libraries/Administrator.py
  app/libraries/Challenge.py
  app/libraries/ChallengeSettings.py
  app/libraries/DatabaseManagement.py
  app/libraries/Student.py
  app/libraries/creds.txt
  app/libraries/utils.py
Labels: backend

#101 Merging completed "ui/admin_login" backend into dev
  app/__init__.py
  app/libraries/Administrator.py
  app/static/css/admin.css
  app/static/css/style.css
  app/static/images/adminpagebackground.jpg
  app/templates/adminbase.html
  app/templates/adminlogin.html
  app/templates/feature.html
  app/templates/registerplayername.html
Labels: ui
